image: docker.autonubil.net/shared/magarac:latest

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - gocache
        - .sonar/cache
        - app/

variables:
    DOCKER_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    DOCKER_RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest
    REPO: gitlab.autonubil.net/terraform/terraform-provider-ciao

stages:
    - validate
    - build

sonar:
    stage: validate
    script:
        - mkdir -p /root/.sonar/cache
        - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=. -Dsonar.login=$SONAR_TOKEN -Duser.home=/root/ -Dsonar.exclusions="client/**, models/**" || true
        - ls -al /root/.sonar/


build:
    stage: build
    script: |
        export ROOT=$(pwd)
        mkdir -p app/
        mkdir -p /root/gocache
        ls -alh
        go get .
        GOCACHE=$ROOT/gocache CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w -linkmode=external -v -X main.Version=$CI_COMMIT_REF_NAME -X main.BuildDate=$(date --iso-8601=seconds) -X main.Commit=$CI_COMMIT_SHA -s" -a -v -o $ROOT/terraform-provider-ciao main.go
        upx $ROOT/terraform-provider-ciao
    artifacts:
      paths:
      - terraform-provider-ciao
    only:
      - master

build_release:
    stage: build
    script: |
        export ROOT=$(pwd)
        mkdir -p app/
        mkdir -p /root/gocache
        ls -alh
        go get .
        GOCACHE=$ROOT/gocache CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w -linkmode=external -v -X main.Version=$CI_COMMIT_REF_NAME -X main.BuildDate=$(date --iso-8601=seconds) -X main.Commit=$CI_COMMIT_SHA -s" -a -v -o $ROOT/terraform-provider-ciao_v$CI_COMMIT_REF_NAME main.go
        upx $ROOT/terraform-provider-ciao_v$CI_COMMIT_REF_NAME
    artifacts:
      paths:
      - terraform-provider-ciao_v$CI_COMMIT_REF_NAME
    only:
      - tags


