include:
  - project: 'exanio/renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
  - project: 'exanio/gitlab/ci-templates'
    ref: main
    file: '/.gitlab-ci-terraform-provider-publish.yml'

before_script:
  - echo "[url \"https://gitlab-ci-token:${RENOVATE_TOKEN}@gitlab.autonubil.net\"] insteadOf = https://gitlab.autonubil.net" >> ~/.gitconfig
